name: Actualizar Datos Meteo

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v4

    - name: Descargar JSON de la API
      run: |
        curl -s "https://climameteoinfo.com{{ secrets.METEO_API_KEY }}&format=json" -o datos.json

    - name: Confirmar y subir cambios
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add datos.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Meteo: Datos actualizados automáticamente" && git push)
