name: Guardar Datos de la Estación

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: 1. Descargar repositorio
      uses: actions/checkout@v4

    - name: 2. Descargar el JSON directo de WeatherLink
      run: |
        curl -s "https://weatherlink.com" -o estacion.json

    - name: 3. Subir el JSON de forma segura al repositorio
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        
        git pull origin HEAD
        git add estacion.json
        
        # CORRECCIÓN: Si no hay cambios, el script muestra un mensaje informativo y finaliza con éxito (exit 0) en vez de fallar
        if git diff-index --quiet HEAD; then
          echo "Los datos meteorológicos no han cambiado. Finalizando con éxito."
          exit 0
        else
          git commit -m "Meteo: Archivo JSON actualizado automáticamente"
          git push https://x-access-token:${GH_TOKEN}@://github.com{{ github.repository }}.git HEAD
        fi
