
name: Guardar Datos de la Estación

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: 1. Descargar repositorio
      uses: actions/checkout@v4

    - name: 2. Descargar el JSON directo de WeatherLink
      run: |
        curl -s "https://api.weatherlink.com/v1/NoaaExt.json?user=001D0AE0D724&pass=semiuncial4&apiToken=BB6FD1E154A74270A0A613E9C2CFAAEE" -o estacion.json

    - name: 3. Publicar JSON de forma automática y rápida
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: . # Sube los archivos de la raíz
        branch: main # Fuerza la subida directa a tu rama principal sin bucles de Git
