name: Actualizar Clima Automático

on:
  schedule:
    # Esto le dice a GitHub que despierte cada 15 minutos
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permite probar el botón a mano cuando quieras

# 1. PERMISOS OBLIGATORIOS: Permite escribir el nuevo clima.json en tu repositorio
permissions:
  contents: write

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4.2.2

    - name: Configurar Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.x'

    - name: Instalar librerías necesarias
      run: pip install requests

    - name: Ejecutar el script del clima
      env:
        WEATHERLINK_API_KEY: ${{ secrets.WEATHERLINK_API_KEY }}
        WEATHERLINK_API_SECRET: ${{ secrets.WEATHERLINK_API_SECRET }}
        WEATHERLINK_STATION_ID: ${{ secrets.WEATHERLINK_STATION_ID }}
      # Nota: Si tu archivo está dentro de una carpeta (ej: scripts), recuerda poner 'python scripts/actualizar_clima.py'
      run: python actualizar_clima.py

    # 2. SOLUCIÓN AL ERROR 127: Usamos una extensión oficial automatizada para hacer el Push sin fallos
    - name: Guardar los cambios en el repositorio
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Actualización automática de datos del clima [skip ci]"
        file_pattern: 'clima.json'
